#+title: prse
#+date: <2023-10-08 Sun>
#+setupfile: ../../setup.org

#+HTML: <template>
#+HTML: <Blog>

prse -> prose

a collection of short stuff I wrote, not long enough to be anything of substance or value.




-----

persistent weed, in the crack,

shallow pool, reflecting attacks.

spalling concrete, resilient shelter

but you wont buckle, under the pressure

<2023-10-08 Sun>

-----

ways to lose memories:

you forget which key, you use for the safe

you forget the safe number, and you cant test your key with every safe

you give the safe to someone else, and they run away with it

you lock the safe, within several other safes, and throw away all the keys

you throw the safe further into the future, for a later you to deal with

<2023-10-08 Sun>


-----

things that remind me of you & the small things you do

is it

standing in the rain, holding a black umbrella

that's alike to texting you, from the comfort of my bed.

or was it

staring out of the window, into the darkness of the storm.

the soft words you speak, wrapping my head.

the touch of your cold hands, that you use to write

extravagant fortresses of sweet, sweet rambling.

the touch of cold stone under my neck, the blossom of blood spreading from it.

<2023-07-26 Wed>


-----

you remind me

of a ghost, That i dont get to see.

appearing every todays, whispering in my ear.

she sacrified her face, for no fortune nor fame.

a deal made with someone worse than the devil.

a deal made with her irrationally driven self.

for someone who thinks and breathes in logic,

I wonder how one could be so stupid.

<2023-07-26 Wed>

-----

I dont get to see

pretty clouds often enough

but fortunately

i can see you


every day and night

somewhere only we know

<2023-09-23 Sat>


------

when you speak of warmth, you make me feel it , but then you end up losing it.

so why do I speak of warmth when I'm hot headed?

<2023-07-30 Sun>

-----

I think i need some sedative

falling victim to the scheduled

it all feels too repetitive

"go buy some milk again"

rise before the sun, work my stress away

try to make the most of the next hour

living life on the daytoday

never gonna falter, but let me sway

from side to side

<2023-05-14 Sun>

-----

leave me be

for i am too tired to argue

and if i do argue

you will end up tireder than me

for that is all i can do

<2023-10-08 Sun>


#+HTML: </Blog>
#+HTML: </template>
